name: Java CI with Maven

on:
  push:
    branches: [ main ]  # Trigger on push to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Use Java 17 (or the version your project uses)
        distribution: 'temurin'  # Use Temurin (Adoptium) JDK

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository  # Cache Maven dependencies
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-

    - name: Build with Maven
      run: mvn -B package --file pom.xml  # Build the project using Maven

    - name: Run tests
      run: mvn test  # Run unit tests

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: target/